### ISSUE TITLE
Consider using standardized variables defined by schema.org

### ISSUE THREAD

**Issue by NGenetzky** [hieuthi/joplin-plugin-life-calendar#2]
Consider using more standarized definitions for the start date and the end date (dob/dod,birth/death).

## example

now:

```yaml
dob: 2016-06-20
# dod: 2020-06-20 # overwrite lifespan
lifespan: 4
```

suggestion 1

```yaml
date: 2016-06-20T10:00:00
#endDate: 2020-06-20T12:00:00
#duration: P4Y
```

## Reference schema.org

duration | Duration | The duration of the item (movie, audio recording, event, etc.) in ISO 8601 date format.
-- | -- | --
Date  or                                 DateTime | The end date and time of the item (in ISO 8601 date format).
startDate | Date  or                                 DateTime | The start date and time of the item (in ISO 8601 date format).
-- | -- | --

[duration](https://schema.org/duration) 	[Duration](https://schema.org/Duration) 	The duration of the item (movie, audio recording, event, etc.) in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601).
[endDate](https://schema.org/endDate) 	[Date](https://schema.org/Date)  or
[DateTime](https://schema.org/DateTime) 	The end date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).
[startDate](https://schema.org/startDate) 	[Date](https://schema.org/Date)  or
[DateTime](https://schema.org/DateTime) 	The start date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).

**Comment by hieuthi** [comment]
Add alias for dob, lifespan, and dod as `startDate`, `duration`, and `endDate` in version v1.3.0 to make it more formal.

**Comment by NGenetzky** [comment]
Thanks @hieuthi !
